### ISSUE TITLE
Establish guidelines for various sprites

### ISSUE THREAD

**Issue by cincospenguinos** [cincospenguinos/We-reGoingHomePrototype#29]
Rearrange existing spritesheets for animation. We need to determine how spritesheets will be arranged to help make the code clean and easy to work with.

**Comment by cincospenguinos** [comment]
@SelfDestructKing, I added some guidelines to the `technology.md` file in the `design_doc` directory. Let me know if they make sense and stuff.

**Comment by SelfDestructKing** [comment]
I think those guidelines make sense and I'll make all the necessary readjustments. You can close the issue whenever you feel.

**Comment by cincospenguinos** [comment]
Awesome. Thank you!
