### ISSUE TITLE
Blow Andre's f*cking gourd with your rad-as-f*ck mouse pointer idea and create pointers good enough to give him confidence in your idea.

### ISSUE THREAD

**Issue by SelfDestructKing** [cincospenguinos/We-reGoingHomePrototype#32]
Create five mouse pointers
- [x] Default
- [x] Interact (hand)
- [x] Move
- [x] Rotate
- [x] Move and Rotate
- [x] Don't get petty if we end up trashing this idea
- [ ] Code up necessary bits to present them

**Comment by SelfDestructKing** [comment]
I've stuck all the pointers under "GUI" in "sprites."

**Comment by cincospenguinos** [comment]
I need to code things up to check and see if this works out well or not.

**Comment by cincospenguinos** [comment]
Actually I'm going to create a separate issue for hooking it up.
