### ISSUE TITLE
Background for the puzzle scene

### ISSUE THREAD

**Issue by cincospenguinos** [cincospenguinos/We-reGoingHomePrototype#48]
- [ ] Miniature tilesheet for puzzle scene
    * Tilesheet is less detailed
- [ ] Tilesheet is included in data directory
- [ ] Background is drawn in PuzzleScene

**Comment by cincospenguinos** [comment]
The tilesheet for the puzzle scene should be abstract enough to apply to any level in the game, but still indicate certain ideas to the player, like walls, doors, obstructions, etc.

**Comment by SelfDestructKing** [comment]
@cincospenguinos So I've uploaded a bit of concept of what I had in my head. The idea is the color palette of the sprite sheet is a fairly neutral monochromatic style, so the colors of the individual pieces can be the main focus. A fortunate side effect would also be a flexible tilesheet that we could use for every dungeon. I've also had in mind this to be a top-down view of the room without the 3/4 perspective. I don't know whether or not that's an issue for you, but if it is I can fix it no problem.

**Comment by cincospenguinos** [comment]
I approve of this thing.
