### ISSUE TITLE
Improve Malkhut winter tileset

### ISSUE THREAD

**Issue by SelfDestructKing** [cincospenguinos/We-reGoingHomePrototype#54]

**Comment by cincospenguinos** [comment]
@SelfDestructKing I'm sure you're way ahead of me here, but consider making the "regular snow" recognizably different from each other--like add more texture to the snow or something.

**Comment by SelfDestructKing** [comment]
@cincospenguinos I have no idea what you mean by "regular snow" do you mean the white tiles? Because if so, I am adding more texture to those
