### ISSUE TITLE
Create doors and panel spritesheet

### ISSUE THREAD

**Issue by cincospenguinos** [cincospenguinos/We-reGoingHomePrototype#57]
This will make panel interaction and door interaction a lot easier.

**Comment by SelfDestructKing** [comment]
@cincospenguinos Do you also want tile sheets for the puzzle version of the sprites?

**Comment by cincospenguinos** [comment]
I don't think so. Only if we have a tilesheet for puzzles as well

**Comment by cincospenguinos** [comment]
@SelfDestructKing I have already done this halfway when I put together #41, but if you could append the panel tiles to the bottom of that spritesheet in the same sort of way as the doors, with one row being unselected and the second row being selected, that would be awesome.

**Comment by SelfDestructKing** [comment]
I'm going to close this for now. If any issues arise, we will reopen it.
