### ISSUE TITLE
Idle animations for room pieces

### ISSUE THREAD

**Issue by cincospenguinos** [cincospenguinos/We-reGoingHomePrototype#67]
- [x] Laser
- [x] Doors
- [x] Panel

**Comment by SelfDestructKing** [comment]
@cincospenguinos The only thing that really needs explanation is the panel. The idea is the emblem blinks on and off continuously. Motion attracts the eye and that sort of thing. The emblem should switch on/off once a second. So every 30 frames you want to have it switch. 

On...one second...off...one second...on...one second...etc.

**Comment by cincospenguinos** [comment]
Got it
